FROM node:24-alpine@sha256:a0b9bf06e4e6193cf7a0f58816cc935ff8c2a908f81e6f1a95432d679c54fbfd
WORKDIR /app
COPY redis-rest/package.json ./package.json
COPY redis-rest/package-lock.json ./package-lock.json
RUN npm ci --omit=dev --ignore-scripts
COPY --chown=node:node redis-rest-proxy.mjs .
USER node
EXPOSE 8080
CMD ["node", "redis-rest-proxy.mjs"]
